apiVersion: apps/v1
kind: Deployment
metadata:
  name: grupo13
  namespace: thymeleaf
spec:
  selector:
    matchLabels:
      app: grupo13
  replicas: 1
  template:
    metadata:
      labels:
         app: grupo13
    spec:
      imagePullSecrets:
         - name: github-secret
      containers:
         - name: grupo13
           image: localhost:5000/grupo_1_3:latest
           ports:
              - containerPort: 8080
          env:
            - name: db_host
            value: "190.146.2.119"
            - name: db_port
            value: "4407"
            - name: db_basedatos
            value: "tabla"
            - name: db_usuario
            value: "grupo_1_3"
            - name: db_contrasena
            value: "grupo_1_3"
            
---
apiVersion: v1
kind: Service
metadata:
  name: grupo13
  namespace: thymeleaf
spec:
#  type: NodePort
  selector:
    app: grupo13
  ports:
    - protocol: TCP
      port: 8080
#      nodePort: 30001
      targetPort: 8080